### ISSUE TITLE
Driver data

### ISSUE THREAD

**Issue by khufkens** [stineb/pep#1]
@stineb @lauramarques 

I was looking into the code, but it seems the driver data is missing in the repo.
Could this be shared (dropbox link etc)?

**Comment by lauramarques** [comment]
@khufkens @stineb 

I have just pushed the missing data needed to perform the demo. Let me know if something else is required.

**Comment by stineb** [comment]
Try to avoid putting data into git repos (unless they are small and text-based). All required data is on Euler: `/cluster/home/bestocke/data/pep`.
